
\n
static inline unsigned long long notrace __rdmsr(unsigned int msr)
static inline void notrace __wrmsr(unsigned int msr, u32 low, u32 high)
static inline unsigned long long native_read_msr(unsigned int msr)
static inline unsigned long long native_read_msr_safe(unsigned int msr, int *err)
static inline void notrace native_write_msr(unsigned int msr, u32 low, u32 high)
static inline int notrace native_write_msr_safe(unsigned int msr, u32 low, u32 high)
static __always_inline unsigned long long rdtsc(void)
static __always_inline unsigned long long rdtsc_ordered(void)
static inline unsigned long long native_read_pmc(int counter)
static inline void wrmsr(unsigned int msr, u32 low, u32 high)
static inline void wrmsrl(unsigned int msr, u64 val)
static inline int wrmsr_safe(unsigned int msr, u32 low, u32 high)
static inline int rdmsrl_safe(unsigned int msr, unsigned long long *p)
static inline int wrmsrl_safe(u32 msr, u64 val)
int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; void rdmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; void wrmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; int rdmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; int rdmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; int wrmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; static inline int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; void rdmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; void wrmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; int rdmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; int rdmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; int wrmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; static inline int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
rdmsr(msr_no, *l, *h)
;return 0; } static inline int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; void rdmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; void wrmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; int rdmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; int rdmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; int wrmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; static inline int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
rdmsr(msr_no, *l, *h)
;return 0; } static inline int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
wrmsr(msr_no, l, h)
;return 0; } static inline int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; void rdmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; void wrmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; int rdmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; int rdmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; int wrmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; static inline int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
rdmsr(msr_no, *l, *h)
;return 0; } static inline int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
wrmsr(msr_no, l, h)
;return 0; } static inline int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
rdmsrl(msr_no, *q)
;return 0; } static inline int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; void rdmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; void wrmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; int rdmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; int rdmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; int wrmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; static inline int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
rdmsr(msr_no, *l, *h)
;return 0; } static inline int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
wrmsr(msr_no, l, h)
;return 0; } static inline int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
rdmsrl(msr_no, *q)
;return 0; } static inline int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
wrmsrl(msr_no, q)
;return 0; } static inline void rdmsr_on_cpus(const struct cpumask *m, u32 msr_no, struct msr *msrs)
int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; void rdmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; void wrmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; int rdmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; int rdmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; int wrmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; static inline int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
rdmsr(msr_no, *l, *h)
;return 0; } static inline int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
wrmsr(msr_no, l, h)
;return 0; } static inline int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
rdmsrl(msr_no, *q)
;return 0; } static inline int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
wrmsrl(msr_no, q)
;return 0; } static inline void rdmsr_on_cpus(const struct cpumask *m, u32 msr_no, struct msr *msrs)
rdmsr_on_cpu(0, msr_no, &(msrs[0].l)
, &(msrs[0].h)
)
; } static inline void wrmsr_on_cpus(const struct cpumask *m, u32 msr_no, struct msr *msrs)
int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; void rdmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; void wrmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; int rdmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; int rdmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; int wrmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; static inline int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
rdmsr(msr_no, *l, *h)
;return 0; } static inline int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
wrmsr(msr_no, l, h)
;return 0; } static inline int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
rdmsrl(msr_no, *q)
;return 0; } static inline int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
wrmsrl(msr_no, q)
;return 0; } static inline void rdmsr_on_cpus(const struct cpumask *m, u32 msr_no, struct msr *msrs)
rdmsr_on_cpu(0, msr_no, &(msrs[0].l)
, &(msrs[0].h)
)
; } static inline void wrmsr_on_cpus(const struct cpumask *m, u32 msr_no, struct msr *msrs)
wrmsr_on_cpu(0, msr_no, msrs[0].l, msrs[0].h)
; } static inline int rdmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; void rdmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; void wrmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; int rdmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; int rdmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; int wrmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; static inline int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
rdmsr(msr_no, *l, *h)
;return 0; } static inline int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
wrmsr(msr_no, l, h)
;return 0; } static inline int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
rdmsrl(msr_no, *q)
;return 0; } static inline int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
wrmsrl(msr_no, q)
;return 0; } static inline void rdmsr_on_cpus(const struct cpumask *m, u32 msr_no, struct msr *msrs)
rdmsr_on_cpu(0, msr_no, &(msrs[0].l)
, &(msrs[0].h)
)
; } static inline void wrmsr_on_cpus(const struct cpumask *m, u32 msr_no, struct msr *msrs)
wrmsr_on_cpu(0, msr_no, msrs[0].l, msrs[0].h)
; } static inline int rdmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
return rdmsr_safe(msr_no, l, h)
; } static inline int wrmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; void rdmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; void wrmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; int rdmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; int rdmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; int wrmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; static inline int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
rdmsr(msr_no, *l, *h)
;return 0; } static inline int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
wrmsr(msr_no, l, h)
;return 0; } static inline int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
rdmsrl(msr_no, *q)
;return 0; } static inline int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
wrmsrl(msr_no, q)
;return 0; } static inline void rdmsr_on_cpus(const struct cpumask *m, u32 msr_no, struct msr *msrs)
rdmsr_on_cpu(0, msr_no, &(msrs[0].l)
, &(msrs[0].h)
)
; } static inline void wrmsr_on_cpus(const struct cpumask *m, u32 msr_no, struct msr *msrs)
wrmsr_on_cpu(0, msr_no, msrs[0].l, msrs[0].h)
; } static inline int rdmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
return rdmsr_safe(msr_no, l, h)
; } static inline int wrmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
return wrmsr_safe(msr_no, l, h)
; } static inline int rdmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; void rdmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; void wrmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; int rdmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; int rdmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; int wrmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; static inline int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
rdmsr(msr_no, *l, *h)
;return 0; } static inline int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
wrmsr(msr_no, l, h)
;return 0; } static inline int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
rdmsrl(msr_no, *q)
;return 0; } static inline int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
wrmsrl(msr_no, q)
;return 0; } static inline void rdmsr_on_cpus(const struct cpumask *m, u32 msr_no, struct msr *msrs)
rdmsr_on_cpu(0, msr_no, &(msrs[0].l)
, &(msrs[0].h)
)
; } static inline void wrmsr_on_cpus(const struct cpumask *m, u32 msr_no, struct msr *msrs)
wrmsr_on_cpu(0, msr_no, msrs[0].l, msrs[0].h)
; } static inline int rdmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
return rdmsr_safe(msr_no, l, h)
; } static inline int wrmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
return wrmsr_safe(msr_no, l, h)
; } static inline int rdmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
return rdmsrl_safe(msr_no, q)
; } static inline int wrmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; void rdmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; void wrmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; int rdmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; int rdmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; int wrmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; static inline int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
rdmsr(msr_no, *l, *h)
;return 0; } static inline int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
wrmsr(msr_no, l, h)
;return 0; } static inline int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
rdmsrl(msr_no, *q)
;return 0; } static inline int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
wrmsrl(msr_no, q)
;return 0; } static inline void rdmsr_on_cpus(const struct cpumask *m, u32 msr_no, struct msr *msrs)
rdmsr_on_cpu(0, msr_no, &(msrs[0].l)
, &(msrs[0].h)
)
; } static inline void wrmsr_on_cpus(const struct cpumask *m, u32 msr_no, struct msr *msrs)
wrmsr_on_cpu(0, msr_no, msrs[0].l, msrs[0].h)
; } static inline int rdmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
return rdmsr_safe(msr_no, l, h)
; } static inline int wrmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
return wrmsr_safe(msr_no, l, h)
; } static inline int rdmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
return rdmsrl_safe(msr_no, q)
; } static inline int wrmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
return wrmsrl_safe(msr_no, q)
; } static inline int rdmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; void rdmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; void wrmsr_on_cpus(const struct cpumask *mask, u32 msr_no, struct msr *msrs)
; int rdmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
; int wrmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
; int rdmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
; int wrmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
; int rdmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; int wrmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
; static inline int rdmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
rdmsr(msr_no, *l, *h)
;return 0; } static inline int wrmsr_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
wrmsr(msr_no, l, h)
;return 0; } static inline int rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
rdmsrl(msr_no, *q)
;return 0; } static inline int wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
wrmsrl(msr_no, q)
;return 0; } static inline void rdmsr_on_cpus(const struct cpumask *m, u32 msr_no, struct msr *msrs)
rdmsr_on_cpu(0, msr_no, &(msrs[0].l)
, &(msrs[0].h)
)
; } static inline void wrmsr_on_cpus(const struct cpumask *m, u32 msr_no, struct msr *msrs)
wrmsr_on_cpu(0, msr_no, msrs[0].l, msrs[0].h)
; } static inline int rdmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 *l, u32 *h)
return rdmsr_safe(msr_no, l, h)
; } static inline int wrmsr_safe_on_cpu(unsigned int cpu, u32 msr_no, u32 l, u32 h)
return wrmsr_safe(msr_no, l, h)
; } static inline int rdmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
return rdmsrl_safe(msr_no, q)
; } static inline int wrmsrl_safe_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
return wrmsrl_safe(msr_no, q)
; } static inline int rdmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
return rdmsr_safe_regs(regs)
; } static inline int wrmsr_safe_regs_on_cpu(unsigned int cpu, u32 regs[8])
\n
    195 u32 msr_no
    183 unsigned int cpu
     65 msr_no
     42 u32 *l
     42 u32 *h
     40 u32 l
     40 u32 h
     39 struct msr *msrs
     38 u64 *q
     36 u64 q
     27 u32 regs[8]
     24 const struct cpumask *mask
     19 l
     19 h
     15 const struct cpumask *m
     13 q
     13 msrs[0].h
     13 0
     11 *l
     11 *h
     10 unsigned int msr
      9 *q
      7 &msrs[0].l
      6 msrs[0].l
      5 u32 low
      5 u32 high
      2 void
      2 u64 val
      1 unsigned long long *p
      1 u32 msr
      1 regs
      1 int *err
      1 int counter
