
static void snbep_uncore_pci_disable_box(struct intel_uncore_box *box)
static void snbep_uncore_pci_enable_box(struct intel_uncore_box *box)
static void snbep_uncore_pci_enable_event(struct intel_uncore_box *box, struct perf_event *event)
static void snbep_uncore_pci_disable_event(struct intel_uncore_box *box, struct perf_event *event)
static u64 snbep_uncore_pci_read_counter(struct intel_uncore_box *box, struct perf_event *event)
static void snbep_uncore_pci_init_box(struct intel_uncore_box *box)
static void snbep_uncore_msr_disable_box(struct intel_uncore_box *box)
static void snbep_uncore_msr_enable_box(struct intel_uncore_box *box)
static void snbep_uncore_msr_enable_event(struct intel_uncore_box *box, struct perf_event *event)
static void snbep_uncore_msr_disable_event(struct intel_uncore_box *box, struct perf_event *event)
static void snbep_uncore_msr_init_box(struct intel_uncore_box *box)
static void snbep_cbox_put_constraint(struct intel_uncore_box *box, struct perf_event *event)
static struct event_constraint * __snbep_cbox_get_constraint(struct intel_uncore_box *box, struct perf_event *event, u64 (*cbox_filter_mask)
(int fields)
)
static u64 snbep_cbox_filter_mask(int fields)
static struct event_constraint * snbep_cbox_get_constraint(struct intel_uncore_box *box, struct perf_event *event)
static int snbep_cbox_hw_config(struct intel_uncore_box *box, struct perf_event *event)
static u64 snbep_pcu_alter_er(struct perf_event *event, int new_idx, bool modify)
static struct event_constraint * snbep_pcu_get_constraint(struct intel_uncore_box *box, struct perf_event *event)
static void snbep_pcu_put_constraint(struct intel_uncore_box *box, struct perf_event *event)
static int snbep_pcu_hw_config(struct intel_uncore_box *box, struct perf_event *event)
void snbep_uncore_cpu_init(void)
static int snbep_qpi_hw_config(struct intel_uncore_box *box, struct perf_event *event)
static void snbep_qpi_enable_event(struct intel_uncore_box *box, struct perf_event *event)
static int snbep_pci2phy_map_init(int devid, int nodeid_loc, int idmap_loc, bool reverse)
int snbep_uncore_pci_init(void)
static void ivbep_uncore_msr_init_box(struct intel_uncore_box *box)
static void ivbep_uncore_pci_init_box(struct intel_uncore_box *box)
static u64 ivbep_cbox_filter_mask(int fields)
static struct event_constraint * ivbep_cbox_get_constraint(struct intel_uncore_box *box, struct perf_event *event)
static int ivbep_cbox_hw_config(struct intel_uncore_box *box, struct perf_event *event)
static void ivbep_cbox_enable_event(struct intel_uncore_box *box, struct perf_event *event)
void ivbep_uncore_cpu_init(void)
static void ivbep_uncore_irp_enable_event(struct intel_uncore_box *box, struct perf_event *event)
static void ivbep_uncore_irp_disable_event(struct intel_uncore_box *box, struct perf_event *event)
static u64 ivbep_uncore_irp_read_counter(struct intel_uncore_box *box, struct perf_event *event)
int ivbep_uncore_pci_init(void)
static u64 knl_cha_filter_mask(int fields)
static struct event_constraint * knl_cha_get_constraint(struct intel_uncore_box *box, struct perf_event *event)
static int knl_cha_hw_config(struct intel_uncore_box *box, struct perf_event *event)
void knl_uncore_cpu_init(void)
static void knl_uncore_imc_enable_box(struct intel_uncore_box *box)
static void knl_uncore_imc_enable_event(struct intel_uncore_box *box, struct perf_event *event)
int knl_uncore_pci_init(void)
static int hswep_ubox_hw_config(struct intel_uncore_box *box, struct perf_event *event)
static u64 hswep_cbox_filter_mask(int fields)
static struct event_constraint * hswep_cbox_get_constraint(struct intel_uncore_box *box, struct perf_event *event)
static int hswep_cbox_hw_config(struct intel_uncore_box *box, struct perf_event *event)
static void hswep_cbox_enable_event(struct intel_uncore_box *box, struct perf_event *event)
static void hswep_uncore_sbox_msr_init_box(struct intel_uncore_box *box)
static int hswep_pcu_hw_config(struct intel_uncore_box *box, struct perf_event *event)
void hswep_uncore_cpu_init(void)
static u64 hswep_uncore_irp_read_counter(struct intel_uncore_box *box, struct perf_event *event)
int hswep_uncore_pci_init(void)
void bdx_uncore_cpu_init(void)
int bdx_uncore_pci_init(void)
static u64 skx_cha_filter_mask(int fields)
static struct event_constraint * skx_cha_get_constraint(struct intel_uncore_box *box, struct perf_event *event)
static int skx_cha_hw_config(struct intel_uncore_box *box, struct perf_event *event)
static void skx_iio_enable_event(struct intel_uncore_box *box, struct perf_event *event)
static int skx_count_chabox(void)
void skx_uncore_cpu_init(void)
static void skx_upi_uncore_pci_init_box(struct intel_uncore_box *box)
static void skx_m2m_uncore_pci_init_box(struct intel_uncore_box *box)
int skx_uncore_pci_init(void)
  44 struct intel_uncore_box *box
  33 struct perf_event *event
  13 void
   6 int fields
   1 u64 *cbox_filter_mask
   1 int nodeid_loc
   1 int new_idx
   1 int idmap_loc
   1 int devid
   1 bool reverse
   1 bool modify
