
\n
ifdef CONFIG_MTRR extern u8 mtrr_type_lookup(u64 addr, u64 end, u8 *uniform)
; extern void mtrr_save_fixed_ranges(void *)
; extern void mtrr_save_state(void)
; extern int mtrr_add(unsigned long base, unsigned long size, unsigned int type, bool increment)
; extern int mtrr_add_page(unsigned long base, unsigned long size, unsigned int type, bool increment)
; extern int mtrr_del(int reg, unsigned long base, unsigned long size)
; extern int mtrr_del_page(int reg, unsigned long base, unsigned long size)
; extern void mtrr_centaur_report_mcr(int mcr, u32 lo, u32 hi)
; extern void mtrr_ap_init(void)
; extern void mtrr_bp_init(void)
; extern void set_mtrr_aps_delayed_init(void)
; extern void mtrr_aps_init(void)
; extern void mtrr_bp_restore(void)
; extern int mtrr_trim_uncached_memory(unsigned long end_pfn)
; extern int amd_special_default_mtrr(void)
;else static inline u8 mtrr_type_lookup(u64 addr, u64 end, u8 *uniform)
ifdef CONFIG_MTRR extern u8 mtrr_type_lookup(u64 addr, u64 end, u8 *uniform)
; extern void mtrr_save_fixed_ranges(void *)
; extern void mtrr_save_state(void)
; extern int mtrr_add(unsigned long base, unsigned long size, unsigned int type, bool increment)
; extern int mtrr_add_page(unsigned long base, unsigned long size, unsigned int type, bool increment)
; extern int mtrr_del(int reg, unsigned long base, unsigned long size)
; extern int mtrr_del_page(int reg, unsigned long base, unsigned long size)
; extern void mtrr_centaur_report_mcr(int mcr, u32 lo, u32 hi)
; extern void mtrr_ap_init(void)
; extern void mtrr_bp_init(void)
; extern void set_mtrr_aps_delayed_init(void)
; extern void mtrr_aps_init(void)
; extern void mtrr_bp_restore(void)
; extern int mtrr_trim_uncached_memory(unsigned long end_pfn)
; extern int amd_special_default_mtrr(void)
;else static inline u8 mtrr_type_lookup(u64 addr, u64 end, u8 *uniform)
return MTRR_TYPE_INVALID; } static inline int mtrr_add(unsigned long base, unsigned long size, unsigned int type, bool increment)
ifdef CONFIG_MTRR extern u8 mtrr_type_lookup(u64 addr, u64 end, u8 *uniform)
; extern void mtrr_save_fixed_ranges(void *)
; extern void mtrr_save_state(void)
; extern int mtrr_add(unsigned long base, unsigned long size, unsigned int type, bool increment)
; extern int mtrr_add_page(unsigned long base, unsigned long size, unsigned int type, bool increment)
; extern int mtrr_del(int reg, unsigned long base, unsigned long size)
; extern int mtrr_del_page(int reg, unsigned long base, unsigned long size)
; extern void mtrr_centaur_report_mcr(int mcr, u32 lo, u32 hi)
; extern void mtrr_ap_init(void)
; extern void mtrr_bp_init(void)
; extern void set_mtrr_aps_delayed_init(void)
; extern void mtrr_aps_init(void)
; extern void mtrr_bp_restore(void)
; extern int mtrr_trim_uncached_memory(unsigned long end_pfn)
; extern int amd_special_default_mtrr(void)
;else static inline u8 mtrr_type_lookup(u64 addr, u64 end, u8 *uniform)
return MTRR_TYPE_INVALID; } static inline int mtrr_add(unsigned long base, unsigned long size, unsigned int type, bool increment)
return -ENODEV; } static inline int mtrr_add_page(unsigned long base, unsigned long size, unsigned int type, bool increment)
ifdef CONFIG_MTRR extern u8 mtrr_type_lookup(u64 addr, u64 end, u8 *uniform)
; extern void mtrr_save_fixed_ranges(void *)
; extern void mtrr_save_state(void)
; extern int mtrr_add(unsigned long base, unsigned long size, unsigned int type, bool increment)
; extern int mtrr_add_page(unsigned long base, unsigned long size, unsigned int type, bool increment)
; extern int mtrr_del(int reg, unsigned long base, unsigned long size)
; extern int mtrr_del_page(int reg, unsigned long base, unsigned long size)
; extern void mtrr_centaur_report_mcr(int mcr, u32 lo, u32 hi)
; extern void mtrr_ap_init(void)
; extern void mtrr_bp_init(void)
; extern void set_mtrr_aps_delayed_init(void)
; extern void mtrr_aps_init(void)
; extern void mtrr_bp_restore(void)
; extern int mtrr_trim_uncached_memory(unsigned long end_pfn)
; extern int amd_special_default_mtrr(void)
;else static inline u8 mtrr_type_lookup(u64 addr, u64 end, u8 *uniform)
return MTRR_TYPE_INVALID; } static inline int mtrr_add(unsigned long base, unsigned long size, unsigned int type, bool increment)
return -ENODEV; } static inline int mtrr_add_page(unsigned long base, unsigned long size, unsigned int type, bool increment)
return -ENODEV; } static inline int mtrr_del(int reg, unsigned long base, unsigned long size)
ifdef CONFIG_MTRR extern u8 mtrr_type_lookup(u64 addr, u64 end, u8 *uniform)
; extern void mtrr_save_fixed_ranges(void *)
; extern void mtrr_save_state(void)
; extern int mtrr_add(unsigned long base, unsigned long size, unsigned int type, bool increment)
; extern int mtrr_add_page(unsigned long base, unsigned long size, unsigned int type, bool increment)
; extern int mtrr_del(int reg, unsigned long base, unsigned long size)
; extern int mtrr_del_page(int reg, unsigned long base, unsigned long size)
; extern void mtrr_centaur_report_mcr(int mcr, u32 lo, u32 hi)
; extern void mtrr_ap_init(void)
; extern void mtrr_bp_init(void)
; extern void set_mtrr_aps_delayed_init(void)
; extern void mtrr_aps_init(void)
; extern void mtrr_bp_restore(void)
; extern int mtrr_trim_uncached_memory(unsigned long end_pfn)
; extern int amd_special_default_mtrr(void)
;else static inline u8 mtrr_type_lookup(u64 addr, u64 end, u8 *uniform)
return MTRR_TYPE_INVALID; } static inline int mtrr_add(unsigned long base, unsigned long size, unsigned int type, bool increment)
return -ENODEV; } static inline int mtrr_add_page(unsigned long base, unsigned long size, unsigned int type, bool increment)
return -ENODEV; } static inline int mtrr_del(int reg, unsigned long base, unsigned long size)
return -ENODEV; } static inline int mtrr_del_page(int reg, unsigned long base, unsigned long size)
ifdef CONFIG_MTRR extern u8 mtrr_type_lookup(u64 addr, u64 end, u8 *uniform)
; extern void mtrr_save_fixed_ranges(void *)
; extern void mtrr_save_state(void)
; extern int mtrr_add(unsigned long base, unsigned long size, unsigned int type, bool increment)
; extern int mtrr_add_page(unsigned long base, unsigned long size, unsigned int type, bool increment)
; extern int mtrr_del(int reg, unsigned long base, unsigned long size)
; extern int mtrr_del_page(int reg, unsigned long base, unsigned long size)
; extern void mtrr_centaur_report_mcr(int mcr, u32 lo, u32 hi)
; extern void mtrr_ap_init(void)
; extern void mtrr_bp_init(void)
; extern void set_mtrr_aps_delayed_init(void)
; extern void mtrr_aps_init(void)
; extern void mtrr_bp_restore(void)
; extern int mtrr_trim_uncached_memory(unsigned long end_pfn)
; extern int amd_special_default_mtrr(void)
;else static inline u8 mtrr_type_lookup(u64 addr, u64 end, u8 *uniform)
return MTRR_TYPE_INVALID; } static inline int mtrr_add(unsigned long base, unsigned long size, unsigned int type, bool increment)
return -ENODEV; } static inline int mtrr_add_page(unsigned long base, unsigned long size, unsigned int type, bool increment)
return -ENODEV; } static inline int mtrr_del(int reg, unsigned long base, unsigned long size)
return -ENODEV; } static inline int mtrr_del_page(int reg, unsigned long base, unsigned long size)
return -ENODEV; } static inline int mtrr_trim_uncached_memory(unsigned long end_pfn)
ifdef CONFIG_MTRR extern u8 mtrr_type_lookup(u64 addr, u64 end, u8 *uniform)
; extern void mtrr_save_fixed_ranges(void *)
; extern void mtrr_save_state(void)
; extern int mtrr_add(unsigned long base, unsigned long size, unsigned int type, bool increment)
; extern int mtrr_add_page(unsigned long base, unsigned long size, unsigned int type, bool increment)
; extern int mtrr_del(int reg, unsigned long base, unsigned long size)
; extern int mtrr_del_page(int reg, unsigned long base, unsigned long size)
; extern void mtrr_centaur_report_mcr(int mcr, u32 lo, u32 hi)
; extern void mtrr_ap_init(void)
; extern void mtrr_bp_init(void)
; extern void set_mtrr_aps_delayed_init(void)
; extern void mtrr_aps_init(void)
; extern void mtrr_bp_restore(void)
; extern int mtrr_trim_uncached_memory(unsigned long end_pfn)
; extern int amd_special_default_mtrr(void)
;else static inline u8 mtrr_type_lookup(u64 addr, u64 end, u8 *uniform)
return MTRR_TYPE_INVALID; } static inline int mtrr_add(unsigned long base, unsigned long size, unsigned int type, bool increment)
return -ENODEV; } static inline int mtrr_add_page(unsigned long base, unsigned long size, unsigned int type, bool increment)
return -ENODEV; } static inline int mtrr_del(int reg, unsigned long base, unsigned long size)
return -ENODEV; } static inline int mtrr_del_page(int reg, unsigned long base, unsigned long size)
return -ENODEV; } static inline int mtrr_trim_uncached_memory(unsigned long end_pfn)
return 0; } static inline void mtrr_centaur_report_mcr(int mcr, u32 lo, u32 hi)
ifdef CONFIG_MTRR extern u8 mtrr_type_lookup(u64 addr, u64 end, u8 *uniform)
; extern void mtrr_save_fixed_ranges(void *)
; extern void mtrr_save_state(void)
; extern int mtrr_add(unsigned long base, unsigned long size, unsigned int type, bool increment)
; extern int mtrr_add_page(unsigned long base, unsigned long size, unsigned int type, bool increment)
; extern int mtrr_del(int reg, unsigned long base, unsigned long size)
; extern int mtrr_del_page(int reg, unsigned long base, unsigned long size)
; extern void mtrr_centaur_report_mcr(int mcr, u32 lo, u32 hi)
; extern void mtrr_ap_init(void)
; extern void mtrr_bp_init(void)
; extern void set_mtrr_aps_delayed_init(void)
; extern void mtrr_aps_init(void)
; extern void mtrr_bp_restore(void)
; extern int mtrr_trim_uncached_memory(unsigned long end_pfn)
; extern int amd_special_default_mtrr(void)
;else static inline u8 mtrr_type_lookup(u64 addr, u64 end, u8 *uniform)
return MTRR_TYPE_INVALID; } static inline int mtrr_add(unsigned long base, unsigned long size, unsigned int type, bool increment)
return -ENODEV; } static inline int mtrr_add_page(unsigned long base, unsigned long size, unsigned int type, bool increment)
return -ENODEV; } static inline int mtrr_del(int reg, unsigned long base, unsigned long size)
return -ENODEV; } static inline int mtrr_del_page(int reg, unsigned long base, unsigned long size)
return -ENODEV; } static inline int mtrr_trim_uncached_memory(unsigned long end_pfn)
return 0; } static inline void mtrr_centaur_report_mcr(int mcr, u32 lo, u32 hi)
} static inline void mtrr_bp_init(void)
\n
     57 void
     54 unsigned long size
     54 unsigned long base
     29 unsigned int type
     29 bool increment
     25 int reg
     16 u8 *uniform
     16 u64 end
     16 u64 addr
     11 unsigned long end_pfn
     10 u32 lo
     10 u32 hi
     10 int mcr
      8 void *
