
static void snb_uncore_msr_enable_event(struct intel_uncore_box *box, struct perf_event *event)
static void snb_uncore_msr_disable_event(struct intel_uncore_box *box, struct perf_event *event)
static void snb_uncore_msr_init_box(struct intel_uncore_box *box)
static void snb_uncore_msr_enable_box(struct intel_uncore_box *box)
static void snb_uncore_msr_exit_box(struct intel_uncore_box *box)
void snb_uncore_cpu_init(void)
static void skl_uncore_msr_init_box(struct intel_uncore_box *box)
static void skl_uncore_msr_enable_box(struct intel_uncore_box *box)
static void skl_uncore_msr_exit_box(struct intel_uncore_box *box)
void skl_uncore_cpu_init(void)
static void snb_uncore_imc_init_box(struct intel_uncore_box *box)
static void snb_uncore_imc_exit_box(struct intel_uncore_box *box)
static void snb_uncore_imc_enable_box(struct intel_uncore_box *box)
static void snb_uncore_imc_disable_box(struct intel_uncore_box *box)
static void snb_uncore_imc_enable_event(struct intel_uncore_box *box, struct perf_event *event)
static void snb_uncore_imc_disable_event(struct intel_uncore_box *box, struct perf_event *event)
static u64 snb_uncore_imc_read_counter(struct intel_uncore_box *box, struct perf_event *event)
static int snb_uncore_imc_event_init(struct perf_event *event)
static int snb_uncore_imc_hw_config(struct intel_uncore_box *box, struct perf_event *event)
int snb_pci2phy_map_init(int devid)
static struct pci_driver *imc_uncore_find_dev(void)
static int imc_uncore_pci_init(void)
int snb_uncore_pci_init(void)
int ivb_uncore_pci_init(void)
int ivb_uncore_pci_init(void)
return imc_uncore_pci_init()
; } int hsw_uncore_pci_init(void)
int bdw_uncore_pci_init(void)
int skl_uncore_pci_init(void)
static void nhm_uncore_msr_disable_box(struct intel_uncore_box *box)
static void nhm_uncore_msr_enable_box(struct intel_uncore_box *box)
static void nhm_uncore_msr_enable_event(struct intel_uncore_box *box, struct perf_event *event)
void nhm_uncore_cpu_init(void)
  19 struct intel_uncore_box *box
  11 void
   8 struct perf_event *event
   1 int devid
