
\n
static inline bool cpu_has_vmx_basic_inout(void)
static inline bool cpu_has_virtual_nmis(void)
static inline bool cpu_has_vmx_preemption_timer(void)
static inline bool cpu_has_vmx_posted_intr(void)
static inline bool cpu_has_load_ia32_efer(void)
static inline bool cpu_has_load_perf_global_ctrl(void)
static inline bool vmx_mpx_supported(void)
static inline bool cpu_has_vmx_tpr_shadow(void)
static inline bool cpu_need_tpr_shadow(struct kvm_vcpu *vcpu)
static inline bool cpu_has_vmx_msr_bitmap(void)
static inline bool cpu_has_secondary_exec_ctrls(void)
static inline bool cpu_has_vmx_virtualize_apic_accesses(void)
static inline bool cpu_has_vmx_ept(void)
static inline bool vmx_umip_emulated(void)
static inline bool cpu_has_vmx_rdtscp(void)
static inline bool cpu_has_vmx_virtualize_x2apic_mode(void)
static inline bool cpu_has_vmx_vpid(void)
static inline bool cpu_has_vmx_wbinvd_exit(void)
static inline bool cpu_has_vmx_unrestricted_guest(void)
static inline bool cpu_has_vmx_apic_register_virt(void)
static inline bool cpu_has_vmx_virtual_intr_delivery(void)
static inline bool cpu_has_vmx_ple(void)
static inline bool vmx_rdrand_supported(void)
static inline bool cpu_has_vmx_invpcid(void)
static inline bool cpu_has_vmx_vmfunc(void)
static inline bool cpu_has_vmx_shadow_vmcs(void)
static inline bool cpu_has_vmx_encls_vmexit(void)
static inline bool vmx_rdseed_supported(void)
static inline bool cpu_has_vmx_pml(void)
static inline bool vmx_xsaves_supported(void)
static inline bool cpu_has_vmx_tsc_scaling(void)
static inline bool cpu_has_vmx_apicv(void)
static inline bool cpu_has_vmx_flexpriority(void)
static inline bool cpu_has_vmx_ept_execute_only(void)
static inline bool cpu_has_vmx_ept_4levels(void)
static inline bool cpu_has_vmx_ept_5levels(void)
static inline bool cpu_has_vmx_ept_mt_wb(void)
static inline bool cpu_has_vmx_ept_2m_page(void)
static inline bool cpu_has_vmx_ept_1g_page(void)
static inline bool cpu_has_vmx_ept_ad_bits(void)
static inline bool cpu_has_vmx_invept_context(void)
static inline bool cpu_has_vmx_invept_global(void)
static inline bool cpu_has_vmx_invvpid(void)
static inline bool cpu_has_vmx_invvpid_individual_addr(void)
static inline bool cpu_has_vmx_invvpid_single(void)
static inline bool cpu_has_vmx_invvpid_global(void)
static inline bool cpu_has_vmx_intel_pt(void)
\n
     46 void
      1 struct kvm_vcpu *vcpu
