
static ktime_t fixup_debug_start(struct pci_dev *dev, void (*fn)
(struct pci_dev *dev)
)
static void fixup_debug_report(struct pci_dev *dev, ktime_t calltime, void (*fn)
(struct pci_dev *dev)
)
static void pci_do_fixups(struct pci_dev *dev, struct pci_fixup *f, struct pci_fixup *end)
void pci_fixup_device(enum pci_fixup_pass pass, struct pci_dev *dev)
static int __init pci_apply_final_quirks(void)
static void quirk_mmio_always_on(struct pci_dev *dev)
static void quirk_mellanox_tavor(struct pci_dev *dev)
static void quirk_passive_release(struct pci_dev *dev)
static void quirk_isa_dma_hangs(struct pci_dev *dev)
static void quirk_tigerpoint_bm_sts(struct pci_dev *dev)
static void quirk_nopcipci(struct pci_dev *dev)
static void quirk_nopciamd(struct pci_dev *dev)
static void quirk_triton(struct pci_dev *dev)
static void quirk_vialatency(struct pci_dev *dev)
static void quirk_viaetbf(struct pci_dev *dev)
static void quirk_vsfx(struct pci_dev *dev)
static void quirk_alimagik(struct pci_dev *dev)
static void quirk_natoma(struct pci_dev *dev)
static void quirk_citrine(struct pci_dev *dev)
static void quirk_nfp6000(struct pci_dev *dev)
static void quirk_extend_bar_to_page(struct pci_dev *dev)
static void quirk_s3_64M(struct pci_dev *dev)
static void quirk_io(struct pci_dev *dev, int pos, unsigned size, const char *name)
static void quirk_cs5536_vsa(struct pci_dev *dev)
static void quirk_io_region(struct pci_dev *dev, int port, unsigned size, int nr, const char *name)
static void quirk_ati_exploding_mce(struct pci_dev *dev)
static void quirk_amd_nl_class(struct pci_dev *pdev)
static void quirk_ali7101_acpi(struct pci_dev *dev)
static void piix4_io_quirk(struct pci_dev *dev, const char *name, unsigned int port, unsigned int enable)
static void piix4_mem_quirk(struct pci_dev *dev, const char *name, unsigned int port, unsigned int enable)
static void quirk_piix4_acpi(struct pci_dev *dev)
static void quirk_ich4_lpc_acpi(struct pci_dev *dev)
static void ich6_lpc_acpi_gpio(struct pci_dev *dev)
static void ich6_lpc_generic_decode(struct pci_dev *dev, unsigned reg, const char *name, int dynsize)
static void quirk_ich6_lpc(struct pci_dev *dev)
static void ich7_lpc_generic_decode(struct pci_dev *dev, unsigned reg, const char *name)
static void quirk_ich7_lpc(struct pci_dev *dev)
static void quirk_vt82c586_acpi(struct pci_dev *dev)
static void quirk_vt82c686_acpi(struct pci_dev *dev)
static void quirk_vt8235_acpi(struct pci_dev *dev)
static void quirk_xio2000a(struct pci_dev *dev)
static void quirk_via_ioapic(struct pci_dev *dev)
static void quirk_via_vt8237_bypass_apic_deassert(struct pci_dev *dev)
static void quirk_amd_ioapic(struct pci_dev *dev)
static void quirk_cavium_sriov_rnm_link(struct pci_dev *dev)
static void quirk_amd_8131_mmrbc(struct pci_dev *dev)
static void quirk_via_acpi(struct pci_dev *d)
static void quirk_via_bridge(struct pci_dev *dev)
static void quirk_via_vlink(struct pci_dev *dev)
static void quirk_vt82c598_id(struct pci_dev *dev)
static void quirk_cardbus_legacy(struct pci_dev *dev)
static void quirk_amd_ordering(struct pci_dev *dev)
static void quirk_dunord(struct pci_dev *dev)
static void quirk_transparent_bridge(struct pci_dev *dev)
static void quirk_mediagx_master(struct pci_dev *dev)
static void quirk_disable_pxb(struct pci_dev *pdev)
static void quirk_amd_ide_mode(struct pci_dev *pdev)
static void quirk_svwks_csb5ide(struct pci_dev *pdev)
static void quirk_ide_samemode(struct pci_dev *pdev)
static void quirk_no_ata_d3(struct pci_dev *pdev)
static void quirk_eisa_bridge(struct pci_dev *dev)
static void asus_hides_smbus_hostbridge(struct pci_dev *dev)
static void asus_hides_smbus_lpc(struct pci_dev *dev)
static void __iomem *asus_rcba_base; static void asus_hides_smbus_lpc_ich6_suspend(struct pci_dev *dev)
static void asus_hides_smbus_lpc_ich6_resume_early(struct pci_dev *dev)
static void asus_hides_smbus_lpc_ich6_resume(struct pci_dev *dev)
static void asus_hides_smbus_lpc_ich6(struct pci_dev *dev)
static void quirk_sis_96x_smbus(struct pci_dev *dev)
static void quirk_sis_503(struct pci_dev *dev)
static void asus_hides_ac97_lpc(struct pci_dev *dev)
static void quirk_jmicron_ata(struct pci_dev *pdev)
static void quirk_jmicron_async_suspend(struct pci_dev *dev)
static void quirk_alder_ioapic(struct pci_dev *pdev)
static void quirk_pcie_mch(struct pci_dev *pdev)
static void quirk_pcie_pxh(struct pci_dev *dev)
static void quirk_intel_pcie_pm(struct pci_dev *dev)
static void quirk_radeon_pm(struct pci_dev *dev)
static int dmi_disable_ioapicreroute(const struct dmi_system_id *d)
static void quirk_reroute_to_boot_interrupts_intel(struct pci_dev *dev)
static void quirk_disable_intel_boot_interrupt(struct pci_dev *dev)
static void quirk_disable_broadcom_boot_interrupt(struct pci_dev *dev)
static void quirk_disable_amd_813x_boot_interrupt(struct pci_dev *dev)
static void quirk_disable_amd_8111_boot_interrupt(struct pci_dev *dev)
static void quirk_tc86c001_ide(struct pci_dev *dev)
static void quirk_plx_pci9050(struct pci_dev *dev)
static void quirk_netmos(struct pci_dev *dev)
static void quirk_e100_interrupt(struct pci_dev *dev)
static void quirk_disable_aspm_l0s(struct pci_dev *dev)
static void fixup_rev1_53c810(struct pci_dev *dev)
static void quirk_p64h2_1k_io(struct pci_dev *dev)
static void quirk_nvidia_ck804_pcie_aer_ext_cap(struct pci_dev *dev)
static void quirk_via_cx700_pci_parking_caching(struct pci_dev *dev)
static void quirk_brcm_5719_limit_mrrs(struct pci_dev *dev)
static void quirk_paxc_bridge(struct pci_dev *pdev)
static void quirk_unhide_mch_dev6(struct pci_dev *dev)
static void quirk_disable_all_msi(struct pci_dev *dev)
static void quirk_disable_msi(struct pci_dev *dev)
static void quirk_amd_780_apc_msi(struct pci_dev *host_bridge)
static int msi_ht_cap_enabled(struct pci_dev *dev)
static void quirk_msi_ht_cap(struct pci_dev *dev)
static void quirk_nvidia_ck804_msi_ht_cap(struct pci_dev *dev)
static void ht_enable_msi_mapping(struct pci_dev *dev)
static void nvenet_msi_disable(struct pci_dev *dev)
static void nvbridge_check_legacy_irq_routing(struct pci_dev *dev)
static int ht_check_msi_mapping(struct pci_dev *dev)
static int host_bridge_with_leaf(struct pci_dev *host_bridge)
static int is_end_of_ht_chain(struct pci_dev *dev)
static void nv_ht_enable_msi_mapping(struct pci_dev *dev)
static void ht_disable_msi_mapping(struct pci_dev *dev)
static void __nv_msi_ht_cap_quirk(struct pci_dev *dev, int all)
static void nv_msi_ht_cap_quirk_all(struct pci_dev *dev)
static void nv_msi_ht_cap_quirk_leaf(struct pci_dev *dev)
static void quirk_msi_intx_disable_bug(struct pci_dev *dev)
static void quirk_msi_intx_disable_ati_bug(struct pci_dev *dev)
static void quirk_msi_intx_disable_qca_bug(struct pci_dev *dev)
static void quirk_hotplug_bridge(struct pci_dev *dev)
static void ricoh_mmc_fixup_rl5c476(struct pci_dev *dev)
static void ricoh_mmc_fixup_r5c832(struct pci_dev *dev)
define VTUNCERRMSK_REG 0x1acdefine VTD_MSK_SPEC_ERRORS (1 << 31)
static void vtd_mask_spec_errors(struct pci_dev *dev)
static void fixup_ti816x_class(struct pci_dev *dev)
static void fixup_mpss_256(struct pci_dev *dev)
static void quirk_intel_mc_errata(struct pci_dev *dev)
static void quirk_intel_ntb(struct pci_dev *dev)
define I915_DEIER_REG 0x4400c static void disable_igfx_irq(struct pci_dev *dev)
static void quirk_remove_d3_delay(struct pci_dev *dev)
static void quirk_broken_intx_masking(struct pci_dev *dev)
static void mellanox_check_broken_intx_masking(struct pci_dev *pdev)
static void quirk_no_bus_reset(struct pci_dev *dev)
static void quirk_no_pm_reset(struct pci_dev *dev)
static void quirk_thunderbolt_hotplug_msi(struct pci_dev *pdev)
static void quirk_apple_poweroff_thunderbolt(struct pci_dev *dev)
static void quirk_apple_wait_for_thunderbolt(struct pci_dev *dev)
static int reset_intel_82599_sfp_virtfn(struct pci_dev *dev, int probe)
static int reset_ivb_igd(struct pci_dev *dev, int probe)
static int reset_chelsio_generic_dev(struct pci_dev *dev, int probe)
static int nvme_disable_and_flr(struct pci_dev *dev, int probe)
static int delay_250ms_after_flr(struct pci_dev *dev, int probe)
int pci_dev_specific_reset(struct pci_dev *dev, int probe)
static void quirk_dma_func0_alias(struct pci_dev *dev)
static void quirk_dma_func1_alias(struct pci_dev *dev)
static void quirk_fixed_dma_alias(struct pci_dev *dev)
static void quirk_use_pcie_bridge_dma_alias(struct pci_dev *pdev)
static void quirk_mic_x200_dma_alias(struct pci_dev *pdev)
static void quirk_bridge_cavm_thrx2_pcie_root(struct pci_dev *pdev)
static void quirk_tw686x_class(struct pci_dev *pdev)
static void quirk_relaxedordering_disable(struct pci_dev *dev)
static void quirk_disable_root_port_attributes(struct pci_dev *pdev)
static void quirk_chelsio_T5_disable_root_port_attributes(struct pci_dev *pdev)
static int pci_quirk_amd_sb_acs(struct pci_dev *dev, u16 acs_flags)
static bool pci_quirk_cavium_acs_match(struct pci_dev *dev)
static int pci_quirk_cavium_acs(struct pci_dev *dev, u16 acs_flags)
static int pci_quirk_xgene_acs(struct pci_dev *dev, u16 acs_flags)
static bool pci_quirk_intel_pch_acs_match(struct pci_dev *dev)
static int pci_quirk_intel_pch_acs(struct pci_dev *dev, u16 acs_flags)
static int pci_quirk_qcom_rp_acs(struct pci_dev *dev, u16 acs_flags)
static bool pci_quirk_intel_spt_pch_acs_match(struct pci_dev *dev)
static int pci_quirk_intel_spt_pch_acs(struct pci_dev *dev, u16 acs_flags)
static int pci_quirk_mf_endpoint_acs(struct pci_dev *dev, u16 acs_flags)
int pci_dev_specific_acs_enabled(struct pci_dev *dev, u16 acs_flags)
static int pci_quirk_enable_intel_lpc_acs(struct pci_dev *dev)
static void pci_quirk_enable_intel_rp_mpc_acs(struct pci_dev *dev)
static int pci_quirk_enable_intel_pch_acs(struct pci_dev *dev)
static int pci_quirk_enable_intel_spt_pch_acs(struct pci_dev *dev)
static int pci_quirk_disable_intel_spt_pch_acs_redir(struct pci_dev *dev)
int pci_dev_specific_enable_acs(struct pci_dev *dev)
int pci_dev_specific_disable_acs_redir(struct pci_dev *dev)
static void quirk_intel_qat_vf_cap(struct pci_dev *pdev)
static void quirk_intel_no_flr(struct pci_dev *dev)
static void quirk_no_ext_tags(struct pci_dev *pdev)
static void quirk_no_ats(struct pci_dev *pdev)
static void quirk_fsl_no_msi(struct pci_dev *pdev)
static void quirk_gpu_hda(struct pci_dev *hda)
int pci_idt_bus_quirk(struct pci_bus *bus, int devfn, u32 *l, int timeout)
static void quirk_switchtec_ntb_dma_alias(struct pci_dev *pdev)
 146 struct pci_dev *dev
  23 struct pci_dev *pdev
   8 u16 acs_flags
   6 int probe
   6 const char *name
   2 void *fn
   2 unsigned size
   2 unsigned reg
   2 unsigned int port
   2 unsigned int enable
   2 struct pci_dev *host_bridge
   1 void
   1 u32 *l
   1 struct pci_fixup *f
   1 struct pci_fixup *end
   1 struct pci_dev *hda
   1 struct pci_dev *d
   1 struct pci_bus *bus
   1 ktime_t calltime
   1 int timeout
   1 int pos
   1 int port
   1 int nr
   1 int dynsize
   1 int devfn
   1 int all
   1 enum pci_fixup_pass pass
   1 const struct dmi_system_id *d
   1 1 << 31
