
\n
extern int acpi_video_register(void)
; extern void acpi_video_unregister(void)
; extern int acpi_video_get_edid(struct acpi_device *device, int type, int device_id, void **edid)
; extern enum acpi_backlight_type acpi_video_get_backlight_type(void)
; extern void acpi_video_set_dmi_backlight_type(enum acpi_backlight_type type)
;extern bool acpi_video_handles_brightness_key_presses(void)
; extern int acpi_video_get_levels(struct acpi_device *device, struct acpi_video_device_brightness **dev_br, int *pmax_level)
; static inline int acpi_video_get_edid(struct acpi_device *device, int type, int device_id, void **edid)
extern int acpi_video_register(void)
; extern void acpi_video_unregister(void)
; extern int acpi_video_get_edid(struct acpi_device *device, int type, int device_id, void **edid)
; extern enum acpi_backlight_type acpi_video_get_backlight_type(void)
; extern void acpi_video_set_dmi_backlight_type(enum acpi_backlight_type type)
;extern bool acpi_video_handles_brightness_key_presses(void)
; extern int acpi_video_get_levels(struct acpi_device *device, struct acpi_video_device_brightness **dev_br, int *pmax_level)
; static inline int acpi_video_get_edid(struct acpi_device *device, int type, int device_id, void **edid)
return -ENODEV; } static inline enum acpi_backlight_type acpi_video_get_backlight_type(void)
extern int acpi_video_register(void)
; extern void acpi_video_unregister(void)
; extern int acpi_video_get_edid(struct acpi_device *device, int type, int device_id, void **edid)
; extern enum acpi_backlight_type acpi_video_get_backlight_type(void)
; extern void acpi_video_set_dmi_backlight_type(enum acpi_backlight_type type)
;extern bool acpi_video_handles_brightness_key_presses(void)
; extern int acpi_video_get_levels(struct acpi_device *device, struct acpi_video_device_brightness **dev_br, int *pmax_level)
; static inline int acpi_video_get_edid(struct acpi_device *device, int type, int device_id, void **edid)
return -ENODEV; } static inline enum acpi_backlight_type acpi_video_get_backlight_type(void)
return acpi_backlight_vendor; } static inline void acpi_video_set_dmi_backlight_type(enum acpi_backlight_type type)
extern int acpi_video_register(void)
; extern void acpi_video_unregister(void)
; extern int acpi_video_get_edid(struct acpi_device *device, int type, int device_id, void **edid)
; extern enum acpi_backlight_type acpi_video_get_backlight_type(void)
; extern void acpi_video_set_dmi_backlight_type(enum acpi_backlight_type type)
;extern bool acpi_video_handles_brightness_key_presses(void)
; extern int acpi_video_get_levels(struct acpi_device *device, struct acpi_video_device_brightness **dev_br, int *pmax_level)
; static inline int acpi_video_get_edid(struct acpi_device *device, int type, int device_id, void **edid)
return -ENODEV; } static inline enum acpi_backlight_type acpi_video_get_backlight_type(void)
return acpi_backlight_vendor; } static inline void acpi_video_set_dmi_backlight_type(enum acpi_backlight_type type)
} static inline bool acpi_video_handles_brightness_key_presses(void)
extern int acpi_video_register(void)
; extern void acpi_video_unregister(void)
; extern int acpi_video_get_edid(struct acpi_device *device, int type, int device_id, void **edid)
; extern enum acpi_backlight_type acpi_video_get_backlight_type(void)
; extern void acpi_video_set_dmi_backlight_type(enum acpi_backlight_type type)
;extern bool acpi_video_handles_brightness_key_presses(void)
; extern int acpi_video_get_levels(struct acpi_device *device, struct acpi_video_device_brightness **dev_br, int *pmax_level)
; static inline int acpi_video_get_edid(struct acpi_device *device, int type, int device_id, void **edid)
return -ENODEV; } static inline enum acpi_backlight_type acpi_video_get_backlight_type(void)
return acpi_backlight_vendor; } static inline void acpi_video_set_dmi_backlight_type(enum acpi_backlight_type type)
} static inline bool acpi_video_handles_brightness_key_presses(void)
return false; } static inline int acpi_video_get_levels(struct acpi_device *device, struct acpi_video_device_brightness **dev_br, int *pmax_level)
\n
     26 void
     16 struct acpi_device *device
     10 void **edid
     10 int type
     10 int device_id
      8 enum acpi_backlight_type type
      6 struct acpi_video_device_brightness **dev_br
      6 int *pmax_level
